spring.application.name=MyStudent
spring.datasource.url=jdbc:mysql://localhost:3306/studentsdb
spring.datasource.username=root
spring.datasource.password=0901204940vn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

spring.security.oauth2.client.registration.google.client-id=568622367882-0n8rbet7guf79n25qbpibhlnr5uoni7l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


